- alias: wws
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/Google Drive File Stream/My Drive/code/wksp-github
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/devel/wws
- alias: gsdmgmt
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/Google Drive File Stream/My Drive/code/wksp-inesc
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/devel/gsd-it-management
- alias: dotyfiles
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/Google Drive File Stream/My Drive/code/wksp-github
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/devel/dotfyles
- alias: mpibrasil
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/Google Drive File Stream/My Drive/code/wksp-pmosocial
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/devel/mpibrasil
- alias: datasets
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/Google Drive File Stream/My Drive/code/wksp-vftsprint
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/devel/datasets
- alias: plots
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/Google Drive File Stream/My Drive/code/wksp-vftsprint
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/devel/organized-plots
- alias: bftsmart
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/Google Drive File Stream/My Drive/code/wksp-vftsprint/2020
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/devel/bftsmart
- alias: vftsmart
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/Google Drive File Stream/My Drive/code/wksp-vftsprint/2020
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/devel/vftsmart
- alias: fabric
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/Google Drive File Stream/My Drive/code/wksp-vftsprint/2020
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/devel/fabric-orderingservice
- alias: sprint
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/Google Drive File Stream/My Drive/code/wksp-vftsprint/prj_vftsprint/code
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/devel/sprint_eval
- alias: kaioken
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/Google Drive File Stream/My Drive/code/wksp-vftsprint/prj_vftsprint/code/kaioken
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/devel/kaioken
- alias: abc
  driver: rsync
  dst:
  - /Volumes/data/Users/dporto/aaa/dir2
  opts:
  - -avh
  - --delete-after
  src: /Volumes/data/Users/dporto/aaa/dir1
